blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/vootelerotov/balancing-services-rest-api/discussions
    about: Ask questions or discuss ideas about the API
